services:
  postgis:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: mapstack
      POSTGRES_PASSWORD: mapstack
      POSTGRES_DB: mapstack
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
